### ISSUE TITLE
Storage does not validate client certificate

### ISSUE THREAD

**Issue by slashben** [kubescape/storage#117]
The current implementation does not validate peer TLS certificates and any client can connect it and pull data. It should only be the Kubernetes API server that is allowed to do queries.

**Comment by matthyx** [comment]
@slashben do we want to fix that?

**Comment by slashben** [comment]
we must, but it should be fairly simple

**Comment by slashben** [comment]
it should be set up in `ClientCA` in the `SecureServingInfo` 
see more here
https://pkg.go.dev/k8s.io/apiserver/pkg/server#SecureServingInfo

**Comment by matthyx** [comment]
> it should be set up in `ClientCA` in the `SecureServingInfo` see more here https://pkg.go.dev/k8s.io/apiserver/pkg/server#SecureServingInfo

nice, do we want to add a config entry for that certificate? or should we read it from somewhere in the downward API?

**Comment by slashben** [comment]
Wait, we have two problems here.

One is we need to have the client certificate of the API server (it can be take with `kubectl get configmap -n kube-public cluster-info -o jsonpath='{.data.kubeconfig}' | yq | jq .clusters[0].cluster."certificate-authority-data"` , I guess we can read it during the helm installation)

The second is that we do not generate server certificate 😞 
```yaml
apiVersion: apiregistration.k8s.io/v1                                                                                                   
kind: APIService                                                                                                                        
metadata:
  spec:                                                                                                                                │
    insecureSkipTLSVerify: true
```
