### ISSUE TITLE
kubectl get vulnerabilitysummaries always return 0 vulnerabilities

### ISSUE THREAD

**Issue by everythings-gonna-be-alright** [kubescape/storage#187]
```
λ kubectl version
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1
```

After storage [v0.0.149](https://github.com/kubescape/storage/releases/tag/v0.0.149), command `kubectl get vulnerabilitysummaries -o yaml` always return 0 ( List ):
```
  spec:
    severities:
      critical:
        all: 0
      high:
        all: 0
      low:
        all: 0
      medium:
        all: 0
      negligible:
        all: 0
      unknown:
        all: 0
```

But if you select specific manifest ( Get ), everything ok:
`kubectl get vulnerabilitysummaries ollama -o yaml`

```
spec:
  severities:
    critical:
      all: 1
    high:
      all: 2
    low:
      all: 37
    medium:
      all: 29
    negligible:
      all: 7
    unknown:
      all: 0
```
